version: '3.4'

services:
  stmmicroservice1.api:
    environment:
     - ASPNETCORE_HTTP_PORTS=8080 #- ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
     - 5000:8080

  stmmicroservice2.api:
    environment:
     - ASPNETCORE_HTTP_PORTS=8080
    ports:
     - 5010:8080
 

  