version: '3.4'

services:
  stmmicroservice1.api:
    image: micro1
    build:
      context: .
      dockerfile: Micro1/Dockerfile

  stmmicroservice2.api:
    image: micro2
    build:
      context: .
      dockerfile: Micro2/Dockerfile
